[project]
name = "mcpserver-local"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kok How, Teh", email = "funcoolgeek@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp>=1.28.1",
]

[project.scripts]
mcpserver-local = "mcpserver:main"
mcpserver-local-cli = "mcpserver.cli:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.build-backend]
module-name = "mcpserver"
module-root = "src"